language: node_js
node_js:
- '10'
cache: npm
script:
- npm run push
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_aecec397e0d1_key -iv $encrypted_aecec397e0d1_iv
  -in .travis.enc -out push.config.js -d
