language: node_js
node_js:
- "8"
cache: npm
before_install:
   - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key 
     -in .travis.enc -out push.config.js -d
script:
- npm push
branches: 
  only: 
  - master 